#!/bin/bash
set -e

_VERSION=$1;
DOCKER_IMAGE=$2

sed -e "s/###VERSION###/${_VERSION}/g" sfpkg.info.tmpl > library/sfpkg.info
(cd library && zip ../signalfx-${_VERSION}.zip sfpkg.info $(find . \( -type d -o \( -type f -a -name "*.flow" \) \)))
rm library/sfpkg.info

docker build --build-arg VERSION="${_VERSION}" -t "${DOCKER_IMAGE}" .
